package dev.dexuby.openaiclient.common;

import com.google.gson.annotations.SerializedName;

public enum Model {

    @SerializedName("gpt-4-1106-preview")
    GPT_4_TURBO,
    @SerializedName("gpt-4-vision-preview")
    GPT_4_TURBO_VISION,
    @SerializedName("gpt-4")
    GPT_4,
    @SerializedName("gpt-4-32k")
    GPT_4_32K,
    @SerializedName("gpt-4-0613")
    GPT_4_JUNE_SNAPSHOT,
    @SerializedName("gpt-4-32k-0613")
    GPT_4_32K_JUNE_SNAPSHOT,
    @Deprecated
    @SerializedName("gpt-4-0314")
    GPT_4_MARCH_SNAPSHOT,
    @Deprecated
    @SerializedName("gpt-4-32k-0314")
    GPT_4_32K_MARCH_SNAPSHOT,
    @SerializedName("gpt-3.5-turbo-1106")
    GPT_3_5_TURBO_UPDATED,
    @SerializedName("gpt-3.5-turbo")
    GPT_3_5_TURBO,
    @SerializedName("gpt-3.5-turbo-16k")
    GPT_3_5_TURBO_16K,
    @SerializedName("gpt-3.5-turbo-instruct")
    GPT_3_5_TURBO_INSTRUCT,
    @Deprecated
    @SerializedName("gpt-3.5-turbo-0613")
    GPT_3_5_TURBO_JUNE_SNAPSHOT,
    @Deprecated
    @SerializedName("gpt-3.5-turbo-16k-0613")
    GPT_3_5_TURBO_16K_JUNE_SNAPSHOT,
    @Deprecated
    @SerializedName("gpt-3.5-turbo-0301")
    GPT_3_5_TURBO_MARCH_SNAPSHOT,
    @Deprecated
    @SerializedName("text-davinci-003")
    TEXT_DAVINCI_3,
    @Deprecated
    @SerializedName("text-davinci-002")
    TEXT_DAVINCI_2,
    @Deprecated
    @SerializedName("code-davinci-002")
    CODE_DAVINCI_2,
    @SerializedName("dall-e-3")
    DALL_E_3,
    @SerializedName("dall-e-2")
    DALL_E_2,
    @SerializedName("tts-1")
    TTS_1,
    @SerializedName("tts-1-hd")
    TTS_1_HD,
    @SerializedName("whisper-1")
    WHISPER_1,
    @SerializedName("text-moderation-latest")
    TEXT_MODERATION_LATEST,
    @SerializedName("text-moderation-stable")
    TEXT_MODERATION_STABLE,
    @SerializedName("babbage-002")
    BABBAGE_2,
    @SerializedName("davinci-002")
    DAVINCI_2,
    @Deprecated
    @SerializedName("text-curie-001")
    GPT_3_TEXT_CURIE_1,
    @Deprecated
    @SerializedName("text-babbage-001")
    GPT_3_TEXT_BABBAGE_1,
    @Deprecated
    @SerializedName("text-ada-001")
    GPT_3_TEXT_ADA_1,
    @Deprecated
    @SerializedName("davinci")
    GPT_3_DAVINCI,
    @Deprecated
    @SerializedName("curie")
    GPT_3_CURIE,
    @Deprecated
    @SerializedName("babbage")
    GPT_3_BABBAGE,
    @Deprecated
    @SerializedName("ada")
    GPT_3_ADA

}
